/*
  AUTO-GENERATED FILE.
  Run: node scripts/generate-seed-filename-tags.mjs

  Env:
    FABRIC_API_KEY (recommended) or FABRIC_ACCESS_TOKEN
    Optional: SEED_TAGS_PAGES, SEED_TAGS_LIMIT, SEED_TAGS_TOP
*/

export const SEED_FILENAME_TAGS: Record<string, number> = {
  "SEQ3": 141,
  "BITMAP": 94,
  "SHIRT TROZER": 82,
  "1COLOR": 73,
  "SADA": 70,
  "GROUP PIC": 68,
  "2COLOR": 50,
  "LADIES": 46,
  "BORING": 33,
  "4COLOR": 30,
  "3COLOR": 22,
  "6COLOR": 18,
  "BAZU": 16,
  "SHIRT PLAZO": 15,
  "5COLOR": 14,
  "LACES": 14,
  "SHAFOON": 14,
  "LONG SHIRT TROZER": 13,
  "COTTON": 12,
  "WINTER COTTON": 12,
  "7COLOR": 10,
  "DUPATA": 10,
  "GALA": 9,
  "HANDMADE": 9,
  "2HEAD": 8,
  "DAMAN EMB": 6,
  "FRONT EMB": 5,
  "PANEL": 5,
  "SHIRT SHARARA": 5,
  "LEFT KALI": 4,
  "TROZER EMB": 4,
  "BACK": 3,
  "DAMAN LACES": 3,
  "GROUP PIC (2)": 3,
  "ORGANZA": 3,
  "PLAZO EMB": 3,
  "RIGHT KALI": 3,
  "8COLOR": 2,
  "BATIK (1)": 2,
  "Charizma": 2,
  "CHATA": 2,
  "Humdum (1)": 2,
  "HZ Collection (2)": 2,
  "KALI": 2,
  "MARIA B": 2,
  "Rangoon Clothing": 2,
  "SHIRT": 2,
  "2 piece": 1,
  "3 piece suit": 1,
  "AB DESIGNER.": 1,
  "ARFA FABRIC": 1,
  "ARFA FABRIC (2)": 1,
  "ASIM JOFA": 1,
  "baap.outall.,": 1,
  "BACK KALI": 1,
  "BAZU EMB": 1,
  "BAZU MOTIF": 1,
};
